version: "2.4"
services:
 mysqldb:
  image: mysql:5.7
  restart: unless-stopped
  environment:
   - MYSQL_ROOT_PASSWORD=rootpass
   - MYSQL_DATABASE=spring      
   - MYSQL_USER=aziz
   - MYSQL_PASSWORD=aziz
  ports:
   - "3306:3306"
  volumes:
   - .m2:/root/.m2
  stdin_open: true
  tty: true